version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_app_c
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    links:
      - redis
      - mysql
    depends_on:
      - mysql
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_PORT: ${SERVER_PORT}
      PASS_EMAIL_GOOGLE: ${PASS_EMAIL_GOOGLE}
      JWT_ACCESS_SECRET_KEY: ${JWT_ACCESS_SECRET_KEY}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      FOLDER_PATH: ${FOLDER_PATH}
      PUBLIC_ID_PREFIX: ${PUBLIC_ID_PREFIX}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_URI: ${REDIS_URI}

  redis:
    image: redis:latest
    container_name: my-redis-container
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
