-- AlterTable
ALTER TABLE `post` ADD COLUMN `image` VARCHAR(191) NULL,
    ADD COLUMN `imagePublicId` VARCHAR(191) NULL,
    ADD COLUMN `link` VARCHAR(191) NULL,
    ADD COLUMN `location` VARCHAR(191) NULL;
